name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true
        type: string

permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
            arch: x64
          - os: macos-latest
            platform: mac
            arch: arm64
          - os: windows-latest
            platform: win
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Build Electron app
        run: npm run build:electron
        env:
          # Set platform-specific environment variables for electron-builder
          ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            dist/
            out/
          retention-days: 30

      - name: Upload to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.zip
            dist/*.tar.gz
            dist/*.snap
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Separate job for creating release with metadata
  create-release:
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate release notes
        id: release_notes
        run: |
          # Get version from tag or input
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi

          # Create release notes
          cat > release_notes.md << EOF
          ## Manifold $VERSION

          ### What's New
          - Data integration and consolidation improvements
          - Enhanced user interface and experience
          - Performance optimizations
          - Bug fixes and stability improvements

          ### Installation

          **macOS:**
          - Download \`Manifold-$VERSION-arm64.dmg\` for Apple Silicon (M1/M2/M3)
          - Download \`Manifold-$VERSION-x64.dmg\` for Intel Macs
          - Open the DMG file and drag Manifold to Applications

          **Windows:**
          - Download \`Manifold Setup $VERSION.exe\`
          - Run the installer and follow the setup wizard

          **Linux:**
          - Download \`Manifold-$VERSION.AppImage\` for most distributions
          - Make executable: \`chmod +x Manifold-$VERSION.AppImage\`
          - Run: \`./Manifold-$VERSION.AppImage\`

          ### System Requirements
          - **macOS:** 10.15 (Catalina) or later
          - **Windows:** Windows 10 or later
          - **Linux:** Ubuntu 18.04+ or equivalent

          ### Support
          - Report issues: [GitHub Issues](https://github.com/${{ github.repository }}/issues)
          - Documentation: [GitHub Wiki](https://github.com/${{ github.repository }}/wiki)

          ---

          **Full Changelog:** https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.ref_name }}
          EOF

          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat release_notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_notes.outputs.VERSION }}
          name: Manifold ${{ steps.release_notes.outputs.VERSION }}
          body: ${{ steps.release_notes.outputs.notes }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
